### ISSUE TITLE
Support for specifying file extensions

### ISSUE THREAD

**Issue by ritcoder** [senchalabs/jsduck#115]
I'm documenting a library where all the files are javascript files but not all of them have .js as the extension. In this library, the entire presentation layer is in javascript but have the extension .webview. My current solution is to copy them over and add .js to the filenames for the documentation to work.

Can the ability to specify the file extensions be supported with .js as the default if not specified. It could be like specifying the other parameters

--jsext=js,webview,script

**Comment by pmishra** [comment]
Is there any improvements in 2016? :) I want to feed directory path to jsduck and I have few files which contain javascript code but there file extension is different. Can we configure jsduck to generate documents for file which contain js code but there file extension is different.

**Comment by nene** [comment]
Currently there's no option to do that. You'd just need to generate a list of files by yourself and feed them all to JSDuck, e.g. use unix `find` command.
