### ISSUE TITLE
Order of Sections created using Custom Tags

### ISSUE THREAD

**Issue by Technical-Writer** [senchalabs/jsduck#301]
I've written several customs tags but can't seem to find a way to control the order in which they appear. e.g. I have a tag that creates a Demos section, and another that Creates a Scopes section. I want the Scopes section to appear before the Demos section. How can I control this?

**Comment by AnnieCyl** [comment]
@nene I also have this problem now. I defined two tags: "expectation" and "execution". I want "execution" to be showed before "expectation", but it is opposite. How can I control their orders?

**Comment by nene** [comment]
You should be able to do this using `:position` config, as explained in https://github.com/senchalabs/jsduck/wiki/Custom-member-types

**Comment by nene** [comment]
See also: https://github.com/senchalabs/jsduck/blob/master/lib/jsduck/tag/member_tag.rb

**Comment by AnnieCyl** [comment]
@nene Ok, I got it. Thanks a lot!
