### ISSUE TITLE
Permission Denied: on mkdir Windows 8.1 x64

### ISSUE THREAD

**Issue by origin1tech** [senchalabs/jsduck#512]
So jsduck is working great however I have this nagging issue that it blows up if I don't manually create the dir first. Since the directory gets blown out on each build this is obviously an issue. 

I'll be building my project using Grunt and commands from Node so I guess I could handle this prior to calling jsduck but thought there might someone that has run across this issue already.

Double checked definitely in Admin Console. Anyway this is what I did to resolve it not a fix but rather a work around. Thought I'd post here for good measure. 

NOTE: in the below the you'll see "utils.Diskio" namespace this is a helper method I use. You'll need to replace that with node's fs as in require('fs'). Then recurse the directory and remove the files/subs or use something like wrench. Regardless the below should get you the idea. 

```
   var exec = require('child_process').exec,
    cmd = 'jsduck --config=docs.json --output docs',
    child;

/* if docs dir exists delete then recreate */
if(utils.Diskio.exists('docs')) {
    utils.Diskio.removeDirRecursive('docs', function(success) {
        if(success)
            buildDocs();
    });
} else {
    buildDocs();
}

/* build up the docs */
function buildDocs() {

    utils.Diskio.makeDir('docs');

    child =  exec(cmd, {}, function (err, stdout, stderr) {
        if(stdout) console.log('notify: ' + stdout);
        if (err !== null) console.log('exec error: ' + err);

    });

    child.on('exit', function (code) {
        setTimeout(function () {
            if(code === 0)
                console.log('> Documentation successfully built.');
            /* kill the child */
            child.kill();
        }, 200);
    });

}
```

**Comment by ct1104** [comment]
I met the same problem,I wonder if there were some advice!
