### ISSUE TITLE
can this support i18n?

### ISSUE THREAD

**Issue by atian25** [senchalabs/jsduck#56]
such as:
@en: xxx
@zh_CN: xxx

**Comment by AnnieCyl** [comment]
@nene 
hi. you said that you might be having support for something that conditionally turn a protion of doc-comment on or off. I wonder have you done that?

**Comment by nene** [comment]
Nope. That idea was not implemented.

**Comment by AnnieCyl** [comment]
@nene 
Are you going to implement?

**Comment by nene** [comment]
Unlikely.

**Comment by AnnieCyl** [comment]
So that means there is no way to solve this problem using jsduck? we can't write annotations in different languages and then generate different documents?

**Comment by nene** [comment]
I suppose not.

I guess one could hack something in front of Markdown processor through which all the strings go. Export all the strings for translation. Translate them separately. Then map the original strings to translated versions. Kind'a similarly to the way how GNU Gettext works.

This all would be much easier though if in addition to JSON export, there would also be a proper JSON import, so one could take the exported JSON, translate that, and feed it back to JSDuck.
