### ISSUE TITLE
More flexible guides paths

### ISSUE THREAD

**Issue by totty90** [senchalabs/jsduck#584]
Instead of having to have a folder for a guide allow me to directly give you the path to the MD file.

**Comment by brian428** [comment]
Was this change ever included in the 6.0.0-beta? Because it's not working with the most recent 6.0.0-beta.exe in the downloads section. Even with a JSON config like:
```
{
    "name": "Home",
    "url": "Home.md",
    "title": "Home",
    "description": ""
}
```

I still end up with the error:
```
Warning: {my path}\Home.md\README.md Guide not found
```

**Comment by nene** [comment]
No. This change was made after 6.0.0-beta release.

**Comment by brian428** [comment]
OK...then could you do an updated release? According to the releases page, the last 6.0.0-beta release was a year and a half ago (November, 2013).

**Comment by nene** [comment]
Yeah... it's been a while. Sorry :( I need to get this done.

**Comment by brian428** [comment]
Thanks!

**Comment by brian428** [comment]
Not to pester, since I know how busy everyone can get. But could we get that new Windows binary up? We're revamping our project build, but we need this change that allows specifying the paths to the MD files. Thanks.

**Comment by brian428** [comment]
Just another bump to see if we can get an updated Windows binary release that incorporates the changes to the markdown path handling?
