### ISSUE TITLE
Allow use of keywords in JavaScript argument names

### ISSUE THREAD

**Issue by chge** [senchalabs/jsduck#595]
Unfortunately, #416 doesn't cover keywords in argument names.

```javascript
function foo(private) {
	return private;
}
```

```
Error: Error while parsing .../foo.js: Invalid JavaScript syntax: Unexpected 'private' on line 1
```

Tried on both `5.3.4` and `6.0.0beta` with `rkelly-remix 0.0.6`.

**Comment by nene** [comment]
Released rkelly-remix 0.0.7 which fixes this. To update run:

    gem update rkelly-remix
