### ISSUE TITLE
Fix Ruby 1.8 build or drop Ruby 1.8

### ISSUE THREAD

**Issue by Krinkle** [senchalabs/jsduck#598]
The Ruby 1.8 build has been failing for about 9 months now.

https://travis-ci.org/senchalabs/jsduck/builds

Should we drop it from the `.travis.yml` file? Or is there hope in fixing it? And more generally, is Ruby 1.8 supported?

**Comment by nene** [comment]
Hi, many thanks for fixing the build. I think it's surely time to drop Ruby 1.8 support.

Sorry for being away for way too long from JSDuck. Finally merged.
