### ISSUE TITLE
Parsing code for property name

### ISSUE THREAD

**Issue by incutonez** [senchalabs/jsduck#599]
Once again, I'm trying to leverage JSDuck (5.3.4) for Node.js, and in particular, for parsing my JugglingDB schema models.  I've got some code that looks like this:

```
module.exports = function(describe, property) {
  /**
   * @class Blah
   * @author Me
   * @docauthor Me
   * @return {Object} Blah
   * @return {Number} return.blah_id
   * @return {String} return.first_name
   */
  var Blah = describe('Blah', function() {
    /** @property */
    property('blah_id', Number);
    /** @property */
    property('first_name', String);
  });
  return Blah;
};
```

I thought I could use the property tag like that, seeing as line 41 of js/property.rb has smarts for ripping something similar out.  Unfortunately, it shows up in the docs as 1 Property, and it's "Object."  Attaching image:

![blah](https://cloud.githubusercontent.com/assets/1584135/5705393/36f6fe72-9a36-11e4-85d9-6fd4b39a2545.png)

Am I using the property tag wrong, and if so, is there another tag I should be using?  If no, is there a way I could custom parse this and create my own tag?

**Comment by nene** [comment]
Well, JSDuck just doesn't understand this syntax you're using for defining the properties. This line 41 that you're referring to understands the ECMAScript standard Object.defineProperty() method.

JSDuck detects both of these properties as nameless with default type "Object" and merges them together as they have the same name. The best you can do is to explicitly document the name and the type:

```
/** @property {String} blah_id */
```

Unfortunately JSDuck provides no way of extending the auto-detection capabilities of built-in or custom tags.

**Comment by incutonez** [comment]
Ah, ok.  That makes sense.  Thanks for the response... I'll close this one.
