### ISSUE TITLE
Are SCSS/CSS classes supported?

### ISSUE THREAD

**Issue by smithwib** [senchalabs/jsduck#600]
If so, can you offer a tip/example on how to set that up?

Thanks in advance -- this tool is fantastic.

**Comment by nene** [comment]
No. Currently one can only document SCSS variables and mixins.

You could implement a custom member type if you really want: https://github.com/senchalabs/jsduck/wiki/Custom-tags

So you could write something like:

```
/**
 * @scss-class some-class-name
 * Some desription.
 */
.some-class-name {
}
```

Having to use an explicit @-tag is quite inconvenient though.

**Comment by rafdulaf** [comment]
But can jsduck (5.x) generate the CSS vars of ExtJS libs ?
I mean that If you compare : 
* official doc http://docs.sencha.com/extjs/4.2.3/#!/api/Ext.panel.Panel 
* and my doc http://releases.ametys.org/api/3.9-dev/#!/api/Ext.panel.Panel
In my doc, you won't find the "CSS Vars" and "CSS Mixins" menus that you can find in the official doc.

What should I add to my command line to have it?

**Comment by nene** [comment]
It definitely can.

Are you sure you are passing to JSDuck the SCSS files of ExtJS as input? They should be located somewhere inside ExtJS release package, not sure about the exact location from the top of my head.

**Comment by rafdulaf** [comment]
Is it packages/ext-theme-base/sass/src?

**Comment by rafdulaf** [comment]
Trying if resources\ext-theme-gray looks better

**Comment by rafdulaf** [comment]
Ok using "/packages/ext-theme-neutral/sass/var" is fine to have all CSSVars.
But I dont have CSSMixins. Still trying :)

**Comment by rafdulaf** [comment]
Finally found how to add "CssVars" and "CssMixins" of the ExtJS files.
Here are the sources directories I'm compiling with jsduck:
            {ext.directory}/src
            {ext.directory}/examples/ux
            {ext.directory}/packages/ext-theme-neutral/sass/var
            {ext.directory}/packages/ext-theme-neutral/sass/src
