### ISSUE TITLE
@deprecated on a method removes code without deprecation warning

### ISSUE THREAD

**Issue by notionslate** [senchalabs/jsduck#602]
Hi, I tried using @deprecated on a class method expecting a deprecation warning to show up in code. Instead, the documentation for this method was removed completely with no warning. Here is the code:

...
                /**
                 * @deprecated 1.1.0  Use {@link CXF.input.TextField.setData}
                 * Sets the text for the text field.
                 * @method setText
                 * @param {String} setStr
                 */
                var setText = function (setStr) {
                    this.setData(setStr);
                };
...

**Comment by vlizard** [comment]
Deprecated methods are turned off by default. You can include them in documentation by clicking "Deprecated" checkbox in the "Show" dropdown in the top right corner near "Filter class members" field.

**Comment by nene** [comment]
Just as vlizard said.
