### ISSUE TITLE
Cant see the product documentation...

### ISSUE THREAD

**Issue by sipi41** [senchalabs/jsduck#604]
When I go to check the software documentation at http://docs.ckeditor.com/#!/guide/dev_toolbar an ugly error appear as follow:

Oops...

Guide dev_toolbarlocation was not found.

Maybe it was renamed to something else?
Or maybe your internet connection has failed?
This would be sad. Hopefully it's just a bug on our side.

Most likely you just followed a broken link inside this very documentation. Go and report it to the authors of the docs.

But if you think it's a bug in JSDuck documentation-generator itself, feel free to open an issue at the JSDuck issue tracker.

Sorry for all this :(

**Comment by nene** [comment]
The link seems to work fine for me.

As you gave no reason why you think this should be a bug in JSDuck itself, I'm closing this.
