### ISSUE TITLE
Popup menu

### ISSUE THREAD

**Issue by artlantis** [senchalabs/jsduck#608]
Hi,

it's not issue but I want to know something. 

Let's say, we would like to generate ExtJS 4.1,4.2 and 5.1 documents. I have created a json file for config options. What I want to know that, is it possible to generate all documents with one command line with popup menu option? 

If it's possible, how? Could you please share a sample config snippet with me? Thanks

**Comment by nene** [comment]
I suppose you are looking for this: https://github.com/senchalabs/jsduck/wiki/Popup-menu

**Comment by artlantis** [comment]
Dear Nene, yes I was looking for that but I want to generate multiple document with one line console command. Because, if I am not mistaken, we should add those snippet ( I mean Popup Menu code block ) into all docs, right?

**Comment by nene** [comment]
JSDuck doesn't support generating multiple sets of docs with one command.

You can write a simple script to achieve that.

**Comment by artlantis** [comment]
Thanks Nene. 

By the way, Nene means Grandmother in Turkish language :)
