### ISSUE TITLE
Update scss @var documentation

### ISSUE THREAD

**Issue by aratcliffe** [senchalabs/jsduck#610]
Currently docs aren't generated for scss variables unless there is a @class declaration at the head of the .scss file. Can you include this in the documentation.

**Comment by nene** [comment]
Good point. I've improved the docs.

- https://github.com/senchalabs/jsduck/wiki/@var
- https://github.com/senchalabs/jsduck/wiki/@scss-mixin

**Comment by aratcliffe** [comment]
Thanks Rene!
