### ISSUE TITLE
Class Ext.app.Controller not found

### ISSUE THREAD

**Issue by simbro** [senchalabs/jsduck#612]
I'm using Sencha Touch 2.4.1, and when I run JSDuck against my /app folder, I get a lot of messages like: "Class Ext.app.Controller not found". Also, the documentation only documents accesors for each class, i.e. the getters and setters for config properties for each class, none of the other methods are documentation, despite having JSDuck annotations.  I'm using JSDuck version 6.0.0 beta. (couldn't get the previous stable version to run).

**Comment by nene** [comment]
Maybe you forgot to also point JSDuck at the Sencha Touch source code?

Try recreating the problem with a single file with just minimal code and some doc-comments inside it. If this also fails, you can easily post the full source code here, so it'll be possible to further investigate the issue.

**Comment by simbro** [comment]
Yes that was my mistake, the following command worked perfectly:

    jsduck ./app ./touch/src --output ./build/docs

Thanks for your help!
