### ISSUE TITLE
Is it possible to document an overloaded function?

### ISSUE THREAD

**Issue by zyklus** [senchalabs/jsduck#622]
I have a function that returns different results based on the incoming data and I want to document it:

```js
(string) => <Number>
(string, Number) => {<Number>number, <Number>offset}
```

is it currently possible to document this properly?

**Comment by nene** [comment]
The best you can do is something like this:

```
/**
 * @param {String} arg1
 * @param {Number} [arg2]
 * @return {(Number | {number: Number, offset: Number})}
 */
```

And then just write in the description that the type of return value depends on the presence of second parameter.

This has been requested before, but there is no special support to document this kind of overloaded functions. So far there are no plans to implement it.
