### ISSUE TITLE
Hacking JSDuck - Recommondations on dependency versions?

### ISSUE THREAD

**Issue by nils-mosbach** [senchalabs/jsduck#625]
I'm currently struggeling slightly with the required versions of compass, sass and ruby in order to get the jsduck build process running on a windows machine. Are there any recommondations?

**Comment by nene** [comment]
This is what I personally currently have:

- Ruby 2.0
- sass 3.4
- compass 1.0.1+

Haven't personally tried to develop it on Windows. There might be unknown problems waiting.

**Comment by nmosbach** [comment]
Thanks nene. :) Which ExtJS version are you using? I downloaded ext-4.1.1a-gpl since that's the one that's linked in the rakefile. 

    error template/resources/sass/docs-ext.scss (D:/Development/business-solutions-jsduck/template/extjs/resources/themes/lib/utils.rb:24:in `[]=': can't modify frozen Array)

As soon as I get this running, I leave some installation notes here for windows. :)
