### ISSUE TITLE
Will this support auto-complete and highlight with the ST3 

### ISSUE THREAD

**Issue by lichenhao** [senchalabs/jsduck#627]
RT~

**Comment by nene** [comment]
Too cryptic message. Unable to decipher.

**Comment by lichenhao** [comment]
Like the Alignment plugin for sublime text 3.

**Comment by nene** [comment]
Sorry, I still don't get it.

- I'm not familiar with the Alignment plugin.
- Auto-complete of what? IMHO there is no auto-complete feature of anything in JSDuck.
- Highlight of what?
- ST3 is what?
