### ISSUE TITLE
rake configure cannot find extjs.zip

### ISSUE THREAD

**Issue by Munawwar** [senchalabs/jsduck#636]
Hi all.
rake configure at line 202 is unable to download ext since the file seems to have moved (or the URl hasn't been updated for a while - http://cdn.sencha.com/ext-4.1.1a-gpl.zip).
I'd like some help as to where I can find similar .zip file?

**Comment by nene** [comment]
Indeed the download has gone off the CDN, and apparently the 4.1.1a being quite old is hard to come by from official sencha.com site... well at least I had no luck finding it.

Finally I managed to find a third-party site that hosted downloads for various ExtJS versions:

- http://olex.openlogic.com/packages/extjs/4.1.1a

Hope this helps.

**Comment by Munawwar** [comment]
Yea, I did get the file from elsewhere. However I kept running into issues. I made some changes that I wanted and generated the gem. However the docs generated just shows a loading gear icon and the network log in Chrome dev tools shows an "app/Application.js?_dc=1451335248414" not found error.

I figured out that when generating Ext4 docs, the output/ folder uses symlinks to app (and few more folders), whereas the docs I've generated for my code doesn't have those files. Either that call is incorrect or the app/ folder should exist. The app seems to be a Sencha SDK 2.0 app or something. 

Also while I do `rake gem` I get warnings like the following:
```
rm: cannot remove ‘template-min/app.jsb3’: No such file or directory
rm: cannot remove ‘template-min/all-classes.js’: No such file or directory
mv: cannot stat ‘template-min/app-all.js’: No such file or directory
```
So I got the SDK 2.0 and sencha touch 2.0, followed the guide [here](http://docs.sencha.com/touch/2.0.2/#!/guide/command), set the variable in sdk-vars.rb and tried making the gem again, and then I started getting new errors/warning during rake gem:
```
Error thown from your application with message: ReferenceError: Can't find variable: Ext
Project file doesn't exist
rm: cannot remove ‘template-min/app.jsb3’: No such file or directory
rm: cannot remove ‘template-min/all-classes.js’: No such file or directory
mv: cannot stat ‘template-min/app-all.js’: No such file or directory
```
I wrangled with it for more than half a day and gave up on jsduck (and was planning to write a quick API docs generation tool with nodejs and (acorn-extract-comments)[https://www.npmjs.com/package/] someday).

**Comment by nene** [comment]
Well, I suppose you could be better off implementing your own tool...

Frankly I haven't done any real maintenance of JSDuck for years now, and meanwhile Sencha has gone off in a much more closed and corporate direction than is appealing for me. So as I'm not working with Sencha tech stack, I don't really have much of an incentive for maintaining JSDuck. Strangely Sencha itself has had no interest in improving JSDuck at all, although they're still using it to generate their own latest docs.

So if you don't create docs for ExtJS/Touch, you don't really need most of the baggage in JSDuck. But if you do use Sencha tech, then you will likely care about having a docs generator that's compatible with the syntax used in ExtJS/Touch source code - and that's really the area where most of the work in JSDuck has gone into - auto-detecting information from ExtJS-specific JavaScript code and being backwards-compatible with all kinds of quirks in `@tags` syntax.

I can give you a hand if you're interesting in doing some development with JSDuck, though I will likely need to debug myself through several steps as well, especially the dev environment setup.

**Comment by Munawwar** [comment]
I don't use Sencha. However I do use kind of an ext inspired [extend()](https://github.com/Munawwar/lithium-ui/blob/master/components/Text.js#L5). And I like the auto-detection which jsduck gives. I've made [my changes](https://github.com/Munawwar/jsduck/commits/master) already to support it. It's only the generation of a working gem (with or without my changes) that I struggled with.

**Comment by fabriciomurta** [comment]
Ext JS 4.1.1a url pointed above no longer works. Just for future reference, I found a copy in the RADIUSdesk sourceforge project; they committed the version in their SVN repository at [revision 238](https://sourceforge.net/p/radiusdesk/code/238/). Download URL would then be: https://sourceforge.net/p/radiusdesk/code/238/tree/extjs/ext-4.1.1a-gpl.zip?format=raw
