### ISSUE TITLE
Unable to install jsduck gem

### ISSUE THREAD

**Issue by Asuza** [senchalabs/jsduck#642]
I tried to run `sudo gem install jsduck` but instead of it working, I got this output:
```
 » sudo gem install jsduck
Fetching: rdiscount-2.1.8.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing jsduck:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h


Gem files will remain installed in /usr/local/share/gems/gems/rdiscount-2.1.8 for inspection.
Results logged to /usr/local/share/gems/gems/rdiscount-2.1.8/ext/gem_make.out
```
Here are possibly helpful versions:
```
 » ruby --version                         
ruby 2.0.0p598 (2014-11-13) [x86_64-linux]
 » gem --version 
2.0.14
```
I don't know what I could have possibly done wrong this soon in the process.

**Comment by nene** [comment]
You seem to have a problem with building native extensions in general (in particular the `rdiscount` gem), as the error tells you it's unable to find Ruby header files. You're probably running a binary distribution of Ruby that doesn't come with header files. You probably need to install some different ruby package or flip some package manager switch depending on your distro.

Anyway... not a problem with JSDuck. You might get more help from StackOverflow.

**Comment by Asuza** [comment]
In case anyone else has this issue, it was fixed for me by installing `ruby-devel`. It is mentioned on [the wiki](https://github.com/senchalabs/jsduck/wiki/Installation), but I didn't see it initially.
