### ISSUE TITLE
Fail parsing template literals

### ISSUE THREAD

**Issue by remss** [senchalabs/jsduck#644]
Using template literals make the parser fail.

    Ext.define('MyPanel' ,{
        extend: 'Ext.panel.Panel',
        myTpl: `
    <div class="test">
        <h1>Hello World!</h1>
        <p>Lorem ipsum...</p>
    </div>`,
        //... other props/methods
    });

 Error while parsing myPanel.js: Invalid JavaScript syntax: Unexpected '`' on line 3

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by nene** [comment]
That's the general issue of JSDuck not supporting ES6 syntax: #630
