### ISSUE TITLE
Viewport specific documentation not opening

### ISSUE THREAD

**Issue by suresh9843** [senchalabs/jsduck#648]
Viewport specific documentation not opening in below link
http://docs.sencha.com/extjs/4.2.2/#!/api/Ext.container.viewport

**Comment by nene** [comment]
That's because you have misspelled Viewport without a capital letter:

- http://docs.sencha.com/extjs/4.2.2/#!/api/Ext.container.Viewport

**Comment by suresh9843** [comment]
Thanks a lot



*Thanks**Suresh*
