### ISSUE TITLE
As requested, bug report with minimal JavaScript required to reproduce.

### ISSUE THREAD

**Issue by sfinktah** [senchalabs/jsduck#652]
dev $ jsduck-5.3.4.exe getOrMakeReduced.js  -o out
    
    Error: Error while parsing getOrMakeReduced.js: something bad happened, please report a bug with sample JavaScript
    
    Here's a full backtrace:
    ...gems/rkelly-remix-0.0.4/lib/rkelly/parser.rb:49:in `yyabort'
    parser.y:534:in `_reduce_254'
    (eval):4:in `_reduce_254'
    (eval):3:in `_racc_do_parse_c'
    (eval):3:in `do_parse'
    ...gems/rkelly-remix-0.0.4/lib/rkelly/parser.rb:43:in `parse'
    ...gems/jsduck-5.3.4/lib/jsduck/js/parser.rb:22:in `parse'
    ...gems/jsduck-5.3.4/lib/jsduck/parser.rb:44:in `parse_js_or_css'
    ...gems/jsduck-5.3.4/lib/jsduck/parser.rb:30:in `parse'
    ...gems/jsduck-5.3.4/lib/jsduck/batch_parser.rb:25:in `block in parse'
    ...gems/jsduck-5.3.4/lib/jsduck/util/parallel.rb:26:in `map'
    ...gems/jsduck-5.3.4/lib/jsduck/util/parallel.rb:26:in `map'
    ...gems/jsduck-5.3.4/lib/jsduck/batch_parser.rb:17:in `parse'
    ...gems/jsduck-5.3.4/lib/jsduck/app.rb:41:in `parse'
    ...gems/jsduck-5.3.4/lib/jsduck/app.rb:21:in `run'
    ...gems/jsduck-5.3.4/bin/jsduck:25:in `<main>'
    
    dev $ cat getOrMakeReduced.js
    function getOrMake(elemQuery, ns) {
        var _target, _targetElem, elem, final, h, s, sections, targetElem;
        h = $(elemQuery);
        if (h.length) {
            return h;
        }
    }

**Comment by sfinktah** [comment]
Aha, it was the _keyword_ (well, it might be a keyword) **final**

**Comment by nene** [comment]
You could try installing newer version of rkelly-remix parser:

```sh
$ gem install rkelly-remix
```

Ah... you're using the windows 5.3.4 binary. Try the 6.0 beta instead. It's not really much of a beta any more... should turn it into a proper release.
