### ISSUE TITLE
Cannot make jsduck on Ubuntu 16.04 / ruby 2.3.1 (jsduck 5.3.x)

### ISSUE THREAD

**Issue by rafdulaf** [senchalabs/jsduck#653]
We used to make our doc with jsduck on an ubuntu 14.04, and it was fine.
We upgraded the server to ubuntu 16.04 and we now encounter the following errors:

`Thread.exclusive is deprecated, use MutexThread.exclusive is deprecated, use Mutex
/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:206:in `block (3 levels) in work_in_processes'
/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:206:in `block (3 levels) in work_in_processes'
Thread.exclusive is deprecated, use Mutex
/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:206:in `block (3 levels) in work_in_processes'
/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:204:in `loop'Thread.exclusive is deprecated, use Mutex
/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:206:in `block (3 levels) in work_in_processes'
/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:204:in `loop'

/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:204:in `loop'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:204:in `block (2 levels) in work_in_processes'
...`

Any idea?
ps: do you think upgrading to 6 would solve this? when will the 6 version be released?

**Comment by nene** [comment]
I don't think version 6 would make much difference.

You could try disabling the parallel processing with `--processes=0`

As the problem seems to come from `parallel` gem, you could try upgrading that independantly. Looks like it has moved on several versions since that JSDuck release - hopefully it's still backwards-compatible.

**Comment by rafdulaf** [comment]
Thanks it works.
