### ISSUE TITLE
How to hide the  Array Boolean item

### ISSUE THREAD

**Issue by mingliao** [senchalabs/jsduck#668]
I am new to use the *jsduck* ,and thanks for the project 👍 
 now i have a question ,when i generator the doc ,the document would generate the *Array* *String* item that I don't need like below 
![image](https://user-images.githubusercontent.com/4270467/29314844-7bc2e308-81f2-11e7-83cb-465ce6a18d5c.png)
how can i hide  these item or delete these item .thank you

**Comment by nene** [comment]
Simply don't use the `--builtin-classes` command line option.

**Comment by mingliao** [comment]
@nene  tks very much 👍
