### ISSUE TITLE
cannot load such file --rubygems.rb

### ISSUE THREAD

**Issue by mingliao** [senchalabs/jsduck#670]
i download the single jsduck.exe  , and put it in my doc folder
when i run  command in my doc folder ,the  console show me the error :
>
```
 in 'require' : cannot load such file --rubygems.rb from <internal:gem_prelude>:1:in '<compiled>'
````

then i follow the [wiki install on windows](https://github.com/senchalabs/jsduck/wiki/Installation#windows)
then i install *ruby*,and *devkit* ,for some reason. i must use *jsduck* in an offline env .   and my friend install the jsduck in an offline env and they don't need to install ruby .and run jsduck with no errors.

i don't know if  i need to reinstall my os system?  or is there another way to use *jsduck*

**Comment by nene** [comment]
Looks like there is some rubygems environment problem, but hard to diagnose. Nobody has reported such error before.

Using the .exe file should be the simplest way to run JSDuck on Windows.

Try to figure out what are the differences between the environments that you and your friend use.

**Comment by mingliao** [comment]
ok ,thank you very much . 👍
