### ISSUE TITLE
why ckfinder not working on hosting

### ISSUE THREAD

**Issue by lyubitelev** [senchalabs/jsduck#675]
ckfinder not working on hosting but local work great, help!

Fatal error: Uncaught CKSource\CKFinder\Exception\CKFinderException: The PHP installation does not meet the minimum system requirements for CKFinder. Missing PHP extensions: Fileinfo. Please refer to CKFinder documentation for more details. in /home/atourkz/a-tour/web/ckfinder/core/connector/php/vendor/cksource/ckfinder/src/CKSource/CKFinder/CKFinder.php:478 Stack trace: #0 /home/atourkz/a-tour/web/ckfinder/core/connector/php/vendor/cksource/ckfinder/src/CKSource/CKFinder/CKFinder.php(500): CKSource\CKFinder\CKFinder->checkRequirements() #1 /home/atourkz/a-tour/web/ckfinder/core/connector/php/vendor/cksource/ckfinder/src/CKSource/CKFinder/CKFinder.php(567): CKSource\CKFinder\CKFinder->boot(Object(Symfony\Component\HttpFoundation\Request)) #2 /home/atourkz/a-tour/web/ckfinder/core/connector/php/vendor/cksource/ckfinder/src/CKSource/CKFinder/CKFinder.php(313): CKSource\CKFinder\CKFinder->handle(Object(Symfony\Component\HttpFoundation\Request)) #3 /home/atourkz/a-tour/web/ckfinder/core/connector/php/connector.php(20): CKSour in /home/atourkz/a-tour/web/ckfinder/core/connector/php/vendor/cksource/ckfinder/src/CKSource/CKFinder/CKFinder.php on line 478

**Comment by nene** [comment]
@lyubitelev I have no idea how this should relate to JSDuck. Therefore I'm closing this issue.

**Comment by lyubitelev** [comment]
@nene php fileinfo module was absent on hosting, thanks!
