### ISSUE TITLE
Have a way to prevent loading external resources

### ISSUE THREAD

**Issue by reedy** [senchalabs/jsduck#678]
Hello!

It'd be really useful if there was a way for sites to not load fonts (jquery etc) from external sites (like fonts.googleapis.com and ajax.googleapis.com)

As these are used in your templates https://github.com/senchalabs/jsduck/search?q=googleapis&unscoped_q=googleapis is it possible to make this user configurable? So I can give in the config a url to jquery, or to the specific fonts, and have that merged into the templates during documentation generation.

Thanks in advance

Sam

**Comment by nene** [comment]
Probably not going to happen as JSDuck is not really maintained any more.

**Comment by reedy** [comment]
Cheers for the heads up and updating the readme to make this apparent

Will see what we want to do at our end :)
